
# Required: A short name for the action package
name: Legal Compliance Package

# Required: A description of what's in the action package.
description: Connects to CRM/ERP and Docs to do things with legal compliance checks.

# Required: The current version of this action package.
version: 0.0.1

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/...

dependencies:
  conda-forge:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  pypi:
  - robocorp-actions=0.2.0
  - faker=24.9.0
  - google-api-python-client=2.125.0
  - google-auth-httplib2=0.2.0
  - google-auth-oauthlib=1.2.0
  - markdown=3.6

